In [1]:
import numpy as np 

In [4]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)

In [12]:
#Yes Their is diff bet variable & array data

In [13]:
print(list_)

[1, 2, 3, 4, 5]


In [14]:
print(array_list)

[1 2 3 4 5]


In [15]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [16]:
for j in array_list:
    print(type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [17]:
array_list = np.array(object = list_, dtype = int)

In [18]:
array_list

array([1, 2, 3, 4, 5])

In [19]:
for new in array_list:
    print(type(new))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [20]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [21]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.shape(num_array)

(2, 3)

In [24]:
np.size(num_array)

6

In [25]:
np.shape(num_list)

(2, 3)

In [26]:
np.size(num_list)

6

In [27]:
new_arr = np.random.randint(1,10 , (3,3))

In [28]:
new_arr

array([[9, 6, 5],
       [8, 8, 7],
       [8, 3, 8]])